project_id = "kzymqlmtysrvnrpcneno"

[functions."github-config"]
verify_jwt = false

[functions."chat"]
verify_jwt = false

[functions."make-plan"]
verify_jwt = false

[functions."admin-get-users"]
verify_jwt = false

[functions."admin-update-user"]
verify_jwt = false

[functions."ai-diagnose"]
verify_jwt = false

[functions."generate-image"]
verify_jwt = false
